In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('../input/fetal-health-classification/fetal_health.csv')

# Gaining Insights

In [3]:
data.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [4]:
data.describe()

baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057                  0.000590   
min               0.000000              0.000000                  0.000000   
25%               0.000000              0.000000                  0.000000   
50%               0.000000              0.000000                  0.000000   
75%               0.003000              0.000000                  0.000000   
max               0.015000              0.001000                  0.005000   

       abnormal_short_term_variability  mean_value_of_short_term_variability  \
count                      2126.000000                           2126.000000   
mean                         46.990122                              1.332785   
std                          17.192814                              0.883241   
min                          12.000000                              0.200000   
25%                          32.000000                              0.700000   
50%                          49.000000                              1.200000   
75%                          61.000000                              1.700000   
max                          87.000000                              7.000000   

       percentage_of_time_with_abnormal_long_term_variability  ...  \
count                                         2126.00000       ...   
mean                                             9.84666       ...   
std                                             18.39688       ...   
min                                              0.00000       ...   
25%                                              0.00000       ...   
50%                                              0.00000       ...   
75%                                             11.00000       ...   
max                                             91.00000       ...   

       histogram_min  histogram_max  histogram_number_of_peaks  \
count    2126.000000    2126.000000                2126.000000   
mean       93.579492     164.025400                   4.068203   
std        29.560212      17.944183                   2.949386   
min        50.000000     122.000000                   0.000000   
25%        67.000000     152.000000                   2.000000   
50%        93.000000     162.000000                   3.000000   
75%       120.000000     174.000000                   6.000000   
max       159.000000     238.000000                  18.000000   

       histogram_number_of_zeroes  histogram_mode  histogram_mean  \
count                 2126.000000     2126.000000     2126.000000   
mean                     0.323612      137.452023      134.610536   
std                      0.706059       16.381289       15.593596   
min                      0.000000       60.000000       73.000000   
25%                      0.000000      129.000000      125.000000   
50%                      0.000000      139.000000      136.000000   
75%                      0.000000      148.000000      145.000000   
max                     10.000000      187.000000      182.000000   

       histogram_median  histogr

In [5]:
X=data.drop('fetal_health',axis=1)

In [6]:
Y=data['fetal_health']

In [7]:
X.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                               43.0       ...   
1                                                0.0       ...   
2                                                0.0       ...   
3                                                0.0       ...   
4                                                0.0       ...   

   histogram_width  histogram_min  histogram_max  histogram_number_of_peaks  \
0             64.0           62.0          126.0                        2.0   
1            130.0           68.0          198.0                        6.0   
2            130.0           68.0          198.0                        5.0   
3            117.0           53.0          170.0                       11.0   
4            117.0           53.0          170.0                        9.0   

   histogram_number_of_zeroes  histogram_mode  histogram_mean  \
0                         0.0           120.0           137.0   
1                         1.0           141.0           136.0   
2                         1.0           141.0           135.0   
3                         0.0           137.0           134.0   
4                         0.0           137.0           136.0   

   histogram_median  histogram_variance  histogram_tendency  
0             121.0                73.0                 1.0  
1             140.0                12.0                 0.0  
2             138.0                13.0                 0.0  
3             137.0                13.0                 1.0  
4             138.0                11.0                 1.0  

[5 rows x 21 columns]

In [8]:
Y.head()

0    2.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: fetal_health, dtype: float64

In [9]:
Y.value_counts()

1.0    1655
2.0     295
3.0     176
Name: fetal_health, dtype: int64

# Data Visualization

In [10]:
import seaborn as sns
sns.pairplot(data, hue='fetal_health', vars=['baseline value','accelerations','fetal_movement','uterine_contractions'])

# Feature Scaling

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X=scaler.fit_transform(X)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

# Spliting the data

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y)

# Linear Kernel SVM

In [13]:
from sklearn.svm import LinearSVC

model = LinearSVC(loss='hinge', dual=True)
model.fit(x_train, y_train)


/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(loss='hinge')

In [14]:
from sklearn.svm import LinearSVC

model = LinearSVC(loss='hinge', dual=True)
model.fit(x_train, y_train)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))


--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.96      0.94      0.95      1268
         2.0       0.68      0.69      0.68       217
         3.0       0.73      0.91      0.81       109

    accuracy                           0.90      1594
   macro avg       0.79      0.85      0.81      1594
weighted avg       0.91      0.90      0.91      1594

------------------      Accuracy      --------- = 0.9040150564617315
CONFUSION MATRIX
[[1193   63   12]
 [  43  149   25]
 [   3    7   99]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.97      0.94      0.95       427
 

/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


# Polynomial Kernel SVM

In [15]:
from sklearn import svm
from sklearn.svm import LinearSVC
model = svm.SVC(kernel='poly', degree=3.7, gamma='auto', coef0=1, C=5)
model.fit(x_train,y_train)
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))

--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.98      0.98      1251
         2.0       0.86      0.89      0.88       213
         3.0       0.96      1.00      0.98       130

    accuracy                           0.97      1594
   macro avg       0.93      0.95      0.94      1594
weighted avg       0.97      0.97      0.97      1594

------------------      Accuracy      --------- = 0.965495608531995
CONFUSION MATRIX
[[1220   30    1]
 [  19  189    5]
 [   0    0  130]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.97      0.94      0.96       428
  

#  Radial Kernel SVM

In [16]:
model = svm.SVC(kernel='rbf', gamma='auto', C=9)
model.fit(x_train, y_train)
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))

--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.99      0.97      0.98      1259
         2.0       0.84      0.89      0.86       209
         3.0       0.93      1.00      0.96       126

    accuracy                           0.96      1594
   macro avg       0.92      0.95      0.93      1594
weighted avg       0.96      0.96      0.96      1594

------------------      Accuracy      --------- = 0.9617314930991218
CONFUSION MATRIX
[[1222   34    3]
 [  17  185    7]
 [   0    0  126]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.95      0.96       429
 

# We have tried three different support vector machine classifiers and Radial Kernal SVM outperforms the other two classifiers